version: '3.8'
services:
  zenswarm-oracle:
    image: ghcr.io/dyne/zenswarm-oracle
    container_name: ${ORACLE_NAME:-zenswarm-oracle}
    build:
      dockerfile: Dockerfile
      tags:
        - ghcr.io/dyne/zenswarm-oracle
    volumes:
      - ${SECRETS:-./secrets}:/var/secrets
      - ./logger:/var/logger
      - ./contracts/${ORACLE_TYPE}:/var/contracts
      - ./contracts/common:/var/common
    environment:
      - LOGGER_DIR=/var/logger
      - HOST=${HOST:-0.0.0.0}
      - HTTP_PORT=${HTTP_PORT}
      - SUBSCRIPTION_FILE=/var/secrets/subscriptions.json
    ports:
      - ${PORT}:3000
    restart: always
